#!/usr/bin/env python3
import os
import urllib.request
import re
import datetime
import xml.etree.ElementTree as ET


CONFIG_PATH = '/conf/config.xml'
UNBOUND_RULES_PATH = '/usr/local/etc/unbound/gamecontrol.conf'

def parse_hosts_from_github(url):
    domains = set()
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'OPNsense-GameControl'})
        with urllib.request.urlopen(req, timeout=10) as response:
            content = response.read().decode('utf-8')
            for line in content.splitlines():
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split()
                if len(parts) >= 2:
                    domain = parts[1]
                    if domain != 'localhost':
                        domains.add(domain)
    except Exception as e:
        print(f"Error downloading list from {url}: {e}")
    return domains

def get_unbound_dnsbl_game_domains(root):
    domains = set()

    # Buscar en todas las estructuras posibles dentro de <OPNsense><Unbound> en config.xml
    # 1. Buscar cualquier nodo cuya descripción sea "Games" o similar
    for elem in root.findall('.//OPNsense/Unbound//'):
        descr = elem.find('description')
        if descr is not None and descr.text and 'game' in descr.text.lower():
            log_msg(f"Se encontró entrada DNSBL que coincide con 'Games': {descr.text}")

            # Buscar URLs
            for child in elem:
                if child.tag in ['url', 'urls', 'type'] and child.text:
                    for u in child.text.split(','):
                        u = u.strip()
                        if u.startswith('http'):
                            log_msg(f"Descargando lista de juegos desde URL: {u}")
                            domains.update(parse_hosts_from_github(u))

                # Buscar Dominios ingresados a mano (Blocklist Domains)
                if child.tag in ['blocklist_domains', 'domains', 'blocklist'] and child.text:
                    log_msg(f"Extrayendo dominios manuales de la entrada 'Games'")
                    for d in child.text.split():
                        d = d.strip()
                        if d and not d.startswith('#'):
                            domains.add(d)

    # 2. Si no se especificó la descripción "Games", buscar URLs directas de GitHub en la configuración de DNSBL
    if not domains:
        for elem in root.findall('.//OPNsense/Unbound//type'):
            if elem.text and 'github' in elem.text.lower():
                log_msg(f"Buscando URL de GitHub en DNSBL: {elem.text}")
                domains.update(parse_hosts_from_github(elem.text))

    # 3. Fallback a la URL por defecto si no se encontró en config.xml
    if not domains:
        gc_url = root.find('.//OPNsense/GameControl/general/github_url')
        url_to_use = gc_url.text if (gc_url is not None and gc_url.text) else "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-only/hosts"
        log_msg(f"Usando URL de respaldo por defecto: {url_to_use}")
        domains.update(parse_hosts_from_github(url_to_use))

    return domains


def log_msg(msg):
    log_file = '/var/log/gamecontrol.log'
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    formatted = f"[{timestamp}] {msg}\n"
    print(formatted.strip())
    try:
        with open(log_file, 'a') as f:
            f.write(formatted)
    except Exception as e:
        pass

def generate_unbound_rules():
    log_msg("Iniciando actualización de reglas DNS GameControl...")
    if not os.path.exists(CONFIG_PATH):
        log_msg(f"ERROR: No se encontró {CONFIG_PATH}")
        return

    tree = ET.parse(CONFIG_PATH)
    root = tree.getroot()
    
    blocked_domains = get_unbound_dnsbl_game_domains(root)
    log_msg(f"Se obtuvieron {len(blocked_domains)} dominios de la lista de juegos de GitHub/DNSBL.")

    # Extraer IPs bloqueadas
    blocked_ips = []
    hosts_elem = root.findall('.//OPNsense/GameControl/hosts/host')
    for host in hosts_elem:
        ip = host.find('ip')
        blocked = host.find('blocked')
        if ip is not None and blocked is not None and blocked.text == '1':
            blocked_ips.append(ip.text)

    log_msg(f"IPs actualmente con bloqueo activo: {len(blocked_ips)}")

    lines = [
        "# Auto-generated by OPNsense GameControl Plugin",
        "server:",
        '    define-tag: "gaming_blocked"',
        '    access-control-tag-action: "gaming_blocked" always_refuse'
    ]

    for ip in blocked_ips:
        lines.append(f'    access-control-tag: {ip}/32 "gaming_blocked"')

    for domain in blocked_domains:
        lines.append(f'    local-zone: "{domain}" inform')
        lines.append(f'    access-control-tag-data: {domain} "gaming_blocked" always_refuse')

    os.makedirs(os.path.dirname(UNBOUND_RULES_PATH), exist_ok=True)
    with open(UNBOUND_RULES_PATH, 'w') as f:
        f.write("\n".join(lines))

    log_msg("Archivo /usr/local/etc/unbound/gamecontrol.conf generado correctamente.")

    res = os.system('/usr/local/sbin/unbound-control reload >/dev/null 2>&1 || /usr/local/sbin/pluginctl -s unbound restart')
    if res == 0:
        log_msg("Unbound recargado exitosamente.")
    else:
        log_msg(f"ADVERTENCIA: Recarga de Unbound retornó código {res}")

if __name__ == '__main__':
    generate_unbound_rules()



