#!/usr/bin/env python3
import os
import json
import datetime
import urllib.request
import urllib.parse

UNBLOCKED_FILE = '/var/etc/gamecontrol_unblocked.json'
LOG_FILE = '/var/log/gamecontrol.log'
ADGUARD_API_URL = 'http://127.0.0.1:3000/control'
GITHUB_GAMES_URL = "https://raw.githubusercontent.com/JosuhaSanhueza/BlockList/refs/heads/main/GamesBlockList.txt"

def log_msg(msg):
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    formatted = f"[{timestamp}] {msg}\n"
    print(formatted.strip())
    try:
        with open(LOG_FILE, 'a') as f:
            f.write(formatted)
    except Exception:
        pass

def parse_hosts_from_github(url):
    domains = set()
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'OPNsense-GameControl'})
        with urllib.request.urlopen(req, timeout=10) as response:
            content = response.read().decode('utf-8')
            for line in content.splitlines():
                line = line.strip()
                if not line or line.startswith('#') or line.startswith('!'):
                    continue
                parts = line.split()
                domain = parts[1] if len(parts) >= 2 else parts[0]
                domain = domain.lstrip('|').rstrip('^').strip()
                if domain and domain != 'localhost' and '.' in domain:
                    domains.add(domain)
    except Exception as e:
        log_msg(f"Error descargando lista de juegos: {e}")
    return sorted(list(domains))

def update_game_control():
    log_msg("Iniciando sincronización con AdGuard Home API...")

    # 1. Cargar dominios de la lista de juegos de GitHub
    domains = parse_hosts_from_github(GITHUB_GAMES_URL)
    log_msg(f"Se obtuvieron {len(domains)} dominios de juegos para AdGuard Home")

    # 2. Leer IPs permitidas desde la web
    unblocked_ips = set()
    if os.path.exists(UNBLOCKED_FILE):
        try:
            with open(UNBLOCKED_FILE, 'r') as f:
                data = json.load(f)
                if isinstance(data, dict):
                    for ip, st in data.items():
                        if st == 0:
                            unblocked_ips.add(ip)
                elif isinstance(data, list):
                    for ip in data:
                        unblocked_ips.add(str(ip))
        except Exception as e:
            log_msg(f"Error leyendo {UNBLOCKED_FILE}: {e}")

    log_msg(f"IPs con juegos permitidos: {len(unblocked_ips)}")

    # 3. Configurar reglas de filtrado por cliente (Rules) en AdGuard Home
    # Generar reglas Adblock ($client) para bloquear los juegos únicamente en las IPs bloqueadas
    user_rules = ["! Auto-generated by OPNsense Escolarapp Game Manager"]
    
    # Agregar dominios a la lista de reglas filtradas por IP de cliente
    for i in range(101, 146):
        ip_addr = f"192.168.12.{i}"
        is_allowed = ip_addr in unblocked_ips
        
        # Si el alumno está bloqueado (botón rojo), agregar sus reglas de bloqueo de juegos
        if not is_allowed:
            for domain in domains:
                user_rules.append(f"||{domain}^$client='{ip_addr}'")

    # Escribir las reglas en la API de AdGuard Home (/control/filtering/set_rules)
    try:
        rules_text = "\n".join(user_rules)
        req = urllib.request.Request(
            f"{ADGUARD_API_URL}/filtering/set_rules",
            data=json.dumps({"rules": rules_text}).encode('utf-8'),
            headers={'Content-Type': 'application/json'},
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            pass
        log_msg("Reglas de juegos sincronizadas con AdGuard Home API exitosamente (0 ms).")
    except Exception as e:
        log_msg(f"Error enviando reglas a AdGuard Home API: {e}")

if __name__ == '__main__':
    update_game_control()








