#!/usr/bin/env python3
import os, json, datetime, urllib.request, urllib.parse

UNBLOCKED_FILE = "/var/etc/gamecontrol_unblocked.json"
LOG_FILE = "/var/log/gamecontrol.log"
ADGUARD_API_URL = "http://127.0.0.1:3000/control"

def log_msg(msg):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted = "[" + timestamp + "] " + str(msg) + "\n"
    print(formatted.strip())
    try:
        with open(LOG_FILE, "a") as f:
            f.write(formatted)
    except Exception:
        pass

def update_game_control():
    log_msg("Sincronizando reglas de excepcion con la API de AdGuard Home...")

    unblocked_ips = set()
    if os.path.exists(UNBLOCKED_FILE):
        try:
            with open(UNBLOCKED_FILE, "r") as f:
                data = json.load(f)
                if isinstance(data, dict):
                    for ip, st in data.items():
                        if st == 0:
                            unblocked_ips.add(ip)
                elif isinstance(data, list):
                    for ip in data:
                        unblocked_ips.add(str(ip))
        except Exception as e:
            log_msg("Error leyendo unblocked file: " + str(e))

    log_msg("IPs con juegos permitidos: " + str(len(unblocked_ips)))

    user_rules = ["! Auto-generated by OPNsense Escolarapp Game Manager"]
    for ip_addr in unblocked_ips:
        user_rules.append("@@||*^$client=" + ip_addr)

    try:
        rules_text = "\n".join(user_rules)
        req = urllib.request.Request(
            ADGUARD_API_URL + "/filtering/set_rules",
            data=json.dumps({"rules": rules_text}).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            log_msg("Reglas de excepcion actualizadas via API exitosamente.")
    except Exception as e:
        log_msg("Advertencia enviando a API: " + str(e))

if __name__ == "__main__":
    update_game_control()
